{{- if .Values.frontend.nginx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ai-quiz-generator.fullname" . }}-nginx
  labels:
    {{- include "ai-quiz-generator.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
data:
  default.conf: |
{{ .Values.frontend.nginx.config | nindent 4 }}
{{- end }}
